pipelines:
  functional-test:
    group: demo-build-test-deploy-as-yaml
    materials:
      upstream-build:
        pipeline: build
        stage: build
    stages:
      - functional-test: 
          jobs:
            test: 
              tasks:
               - exec: 
                   command: ls
                   arguments: "-l"
